# Generated by Django 3.1.7 on 2021-02-25 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DailyTaskApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='task',
            name='task_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
